{{- if .Values.createCIDR }}
apiVersion: networking.x-k8s.io/v1
kind: ClusterCIDR
metadata:
  name: {{ .Release.Name }}-clustercidr
spec:
  perNodeHostBits: {{ .Values.clusterCIDR.perNodeHostBits }}
  ipv4: {{ .Values.clusterCIDR.ipv4CIDR }}
{{- end }}
